name: Amazon SSM agent releases

on:
  push:
    tags: [ '*.*.*.*', '*.*.*.*-*'  ]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
      if: startsWith(github.ref, 'refs/tags/')

  build:
    needs: [ release ]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        goos: [ "linux", "darwin" ]
        goarch: [ "amd64", "arm64" ]

    steps:
    - uses: actions/checkout@v3

    - name: install make and zip
      run: sudo apt-get -qq update && sudo apt-get install -y -qq make zip

    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: build
      run: make -f Makefile.release build-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: upload release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.zip
      if: startsWith(github.ref, 'refs/tags/')
